[Eth]
NetworkId = 56
NoPruning = false
NoPrefetch = false
LightPeers = 100
TrieTimeout = 150000000000
TriesInMemory = 32
EnablePreimageRecording = false

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000
Noverify = false


[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000
Lifetime = 600000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000


[Node]
DataDir = ""
InsecureUnlockAllowed = false
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8545
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 100
NoDiscovery = true
BootstrapNodes = []
StaticNodes = [<get the node list for validators>]
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FileRoot = ""
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
